NFT Resolve Transfer Approved Account Parameter Patch Fix
near/NEPs pull request #303
Opened 2021-12-20 17:22 UTC by BenKurrek

Changed the approved account IDs parameter in nft_resolve_transfer to be type Record<string, number> instead of string[]. 

Fixes #301

2021-12-20 17:28 UTC, mikedotexe commented on specs/Standards/NonFungibleToken/Core.md
>    owner_id: string,
This is one line higher than I can easily make a commit suggestion, would you mind changing this line to be `owner__id`, as it currently says `sender_id` (in the comments)
https://github.com/near/NEPs/pull/303/files#diff-9132c1e8e04717bd55ad822800135f4094e4814a1d5fdb50e86d1204681dbf8eR156

2021-12-20 17:29 UTC, mikedotexe commented on specs/Standards/NonFungibleToken/Core.md
>  // * `approved_token_ids`: if using Approval Management, contract MUST provide
```suggestion
// * `approved_account_ids `: if using Approval Management, contract MUST provide
```

2021-12-20 17:30 UTC, mikedotexe approved these changes
Sounds good to me, a couple of minor fixes could be made in the comments section

2021-12-20 17:34 UTC, mikedotexe requested changes
Actually, can we please bump the patch version? And by this I mean at the top of this Core page, have it be Version 1.0.1

2021-12-20 17:39 UTC, mikedotexe approved these changes
Actually, can we please bump the patch version? And by this I mean at the top of this Core page, have it be Version 1.0.1

2021-12-23 01:35 UTC, austinabell approved these changes
Yeah, this seems correct to me, I thought this had already been updated. Maybe it's worth documenting what the approval IDs would be without the approval standard? I'm not even sure, and seems like the values can be anything, but not sure if this is intentional?

2021-12-23 16:38 UTC, merged