Add delegate keys
near/NEPs pull request #342
Opened 2022-03-27 23:30 UTC by ilblackdragon

TBD

2022-04-01 12:06 UTC, jlogelin requested changes
Content looks great, mostly cosmetic and structural change requests here.

2022-04-01 17:14 UTC, jlogelin requested changes

2022-04-01 17:14 UTC, jlogelin commented on specs/DataStructures/AccessKey.md
> +
Please add the following warning section:
```
:::caution
This is part of proposed spec [NEP-342](https://github.com/near/NEPs/blob/master/neps/nep-0342.md) and subject to change.
:::
```

2022-04-01 17:14 UTC, jlogelin commented on specs/RuntimeSpec/Actions.md
> +
Please add the following warning section:
```
:::caution
This is part of proposed spec [NEP-342](https://github.com/near/NEPs/blob/master/neps/nep-0342.md) and subject to change.
:::
```

2023-02-14 18:11 UTC, ori-near commented
Hi @ilblackdragon (or anyone who is interested in championing this NEP forward), we are cleaning the NEP backlog and noticed that this PR is still in "Draft" mode. Therefore, we are re-labeling this PR as "Needs author revision."

Please ping the @near/nep-moderators once you are ready for us to review it. We will review it again in April, unless we hear from you sooner. We typically close NEPs that are inactive for more than two months, so please let us know if you need more time.

2023-03-13 16:38 UTC, DavidM-D commented
@itegulov might be

2023-11-21 07:47 UTC, ilblackdragon commented
This is outdated now. Thanks!

2023-11-21 07:47 UTC, closed without merging