Fix some formatting issues in Consensus.md
near/NEPs pull request #388
Opened 2022-09-07 20:19 UTC by robin-near

2022-09-18 22:10 UTC, mfornet approved these changes

2022-09-26 14:51 UTC, frol commented on specs/ChainSpec/Consensus.md
> +There's a parameter $\operatorname{epoch\textunderscore length} \ge 3$ that defines the minimum length of an epoch. Suppose that a particular epoch $e_{cur}$ started at height $h$, and say the next e
`\textunderscore` renders literally

<img width="983" alt="image" src="https://user-images.githubusercontent.com/304265/192308359-dec51c49-bd33-41ab-b1ba-081104da6f12.png">

Is there another way to fix it? 🤔

2022-09-26 14:55 UTC, frol requested changes
@robin-near I have fixed the preview deployment and we should fix the formatting there (see my message above)

2022-09-26 19:11 UTC, robin-near commented
OK the underscores should be fixed now. Thanks!

2022-09-26 23:36 UTC, frol approved these changes

2022-09-26 23:36 UTC, merged