nep-393: add bool return to sbt_revoke_by_owner
near/NEPs pull request #510
Opened 2023-09-25 08:14 UTC by robert-zaremba

In the [reference](https://github.com/near-ndc/i-am-human/blob/cfc92b1/contracts/registry/src/registry.rs#L362) implementation we return `bool` in the `registry.sbt_revoke_by_owner` to signal if the operation should continue or it's finished.

We forgot to push this update to the standard.

This update also makes the API consistent with `sbt_recover` and `sbt_soul_transfer`

2023-09-25 09:05 UTC, sczembor commented
This change enhances the method to maintain consistency with other methods that may run a risk of running out of gas and require repeated execution. Consequently, it eliminates the necessity for an extra view call to verify the completion status of the revocation process.

2023-09-26 20:06 UTC, KazanderDad approved these changes
This change adds a boolean to signal if the operation is finished, which ensures consistency with other methods that may run a risk of running out of gas and require repeated execution. If the result is false then the method should be called again until true is returned. This also eliminates the necessity for an extra view call to verify the completion status of the revocation process.

2023-10-02 19:15 UTC, frol requested changes

2023-10-02 19:15 UTC, frol commented on neps/nep-0393.md
> +    /// at most `MAX_REVOKE_PER_CALL` tokens (to fit into the tx gas limit),
What is `MAX_REVOKE_PER_CALL`? It is the only reference here in this document. I believe it should be removed here.

2023-10-22 13:12 UTC, frol approved these changes

2023-10-22 13:13 UTC, merged