NEP-514: Reducing the number of Block Producer Seats in `testnet`
near/NEPs pull request #514
Opened 2023-10-25 16:49 UTC by nikurt

2023-10-26 10:11 UTC, gmilescu approved these changes
The NEP looks good. Adapting the testnet size to the existing number of nodes simplifies testing.

2023-10-27 08:43 UTC, nikurt commented
ping @frol @ori-near

2023-11-01 11:28 UTC, nikurt commented
Begging @frol and @ori-near for a review

2023-11-01 19:17 UTC, frol requested changes
Thank you @nikurt for submitting this NEP, and sorry for the delay.

As a moderator, I reviewed this NEP and it meets [the proposed template guidelines](https://github.com/near/NEPs/blob/master/nep-0000-template.md).

Since I see that the request comes from nearcore team and is approved by subject matter experts (@gmilescu and @wacban [on reference implementation PR]), I believe we should have moved to [the REVIEW stage](https://github.com/near/NEPs/blob/master/neps/nep-0001.md#nep-lifecycle) with @near/wg-protocol working group members reviewing and voting on it, BUT it seems that the PR to nearcore seems to be already merged, so I guess this is just a formality now. Overall, I don't want to make this process unnecessarily hard, so I am fine to rely on just a single vote from Protocol WG (@bowenwang1996, do you want to cast your Protocol WG vote here?)

2023-11-01 19:17 UTC, frol commented on neps/nep-0514.md
> +|   2 |         |            |        |
Given that Benefits and Concerns are already summarized in "Consequences" section, the benefits and concerns may be skipped here, but we still need to capture how the decision has been made. Here is an example:

```suggestion
### 1.0.0 - Initial Version

The Protocol Working Group members approved this NEP on MMM DD, 2023
```

2023-11-03 09:54 UTC, nikurt commented
@bowenwang1996 @mfornet @birchmd Please take a look

2023-11-03 14:56 UTC, bowenwang1996 approved these changes
Looks good to me

2023-11-03 22:02 UTC, frol approved these changes
Based on my previous comment and getting LGTM from the Protocol WG, I approve and merge this PR

2023-11-03 22:02 UTC, merged