nep-393: add class metadata interface
near/NEPs pull request #528
Opened 2024-01-25 17:50 UTC by robert-zaremba

In https://github.com/near/NEPs/pull/393 we defined Issuer (an entity authorized to mint SBTs in the registry) and SBT Class. We also defined Issuer Metadata and Token Metadata, but we didn't provide interface for class metadata. This was implemented in the reference implementation (in one of the subsequent revisions), but was not backported to the NEP. In this PR

* we fix the name of the issuer interface from `SBTContract` to `SBTIssuer`. The original name is wrong and we oversight it in reviews. We talk everywhere about the issuer entity and issuer contract (even the header is _SBT Issuer interface_).
* Renames `ContractMetadata` to `IssuerMetadata`.
* added `ClassMetadata` struct and `sbt_class_metadata` function to the `SBTIssuer`.

2024-01-26 12:45 UTC, frol commented
Thank you @robert-zaremba for submitting this NEP.

As a moderator, I reviewed this NEP and it meets [the proposed template guidelines](https://github.com/near/NEPs/blob/master/nep-0000-template.md). I am moving this NEP to [the REVIEW stage](https://github.com/near/NEPs/blob/master/neps/nep-0001.md#nep-lifecycle) and would like to ask the @near/wg-contract-standards working group members to assign 2 Technical Reviewers to complete a technical review (see expectations below).

Just for clarity, _Technical Reviewers play a crucial role in scaling NEAR ecosystem_ as they provide their in-depth expertise in the niche topic while work group members can stay on guard of the NEAR ecosystem. The discussions may get too deep and it would be inefficient for each WG member to dive into every single comment, so NEAR Developer Governance [designed this process](https://github.com/near/NEPs/blob/master/neps/nep-0001.md) that includes subject matter experts helping us to scale by writing a summary with the raised concerns and how they were addressed.

<details>

<summary>Technical Review Guidelines</summary>

 

* First, review the proposal within one week. If you have any suggestions that could be fixed, leave them as comments to the author. It may take a couple of iterations to resolve any open comments. 

* Second, once all the suggestions are addressed, produce a Technical Summary, which helps the working group members make a weighted decision faster. Without the summary, the working group will have to read the whole discussion and potentially miss some details.

Technical Summary guidelines:

  * A recommendation for the working group if the NEP is ready for voting (it could be approving or rejecting recommendation). Please note that this is the reviewer's personal recommendation.

  * A summary of benefits that surfaced in previous discussions. This should include a concise list of all the benefits that others raised, not just the ones that the reviewer personally agrees with.

  *  A summary of concerns or blockers, along with their current status and resolution. Again, this should reflect the collective view of all commenters, not just the reviewer's perspective.

Here is a [nice example](https://github.com/near/NEPs/pull/399#issuecomment-1462492128) and a template for your convenience:

```

### Recommendation

Add recommendation

### Benefits

* Benefit

* Benefit

### Concerns

| # | Concern | Resolution | Status |

| - | - | - | - |

| 1 | Concern | Resolution | Status |

| 2 | Concern | Resolution | Status |

```

Please tag the @near/nep-moderators once you are done, so we can move this NEP to the voting stage. Thanks again.

</details>

2024-01-29 13:03 UTC, fadeevab requested changes
### Recommendation

Fix the broken references in the documentation, typos, and wording.

### Benefits

Overall, the patch is not complex, everything looks fine.

### Concerns

| # | Concern | Resolution | Status |
| - | - | - | - |
| 1 | Broken references after renaming the struct | Fixes suggested | Done |
| 2 | Wording and typos | Fixes suggested | Done |

2024-01-29 15:04 UTC, fadeevab approved these changes
All suggestions are implemented, table updated: https://github.com/near/NEPs/pull/528#pullrequestreview-1848562574

2024-01-30 04:22 UTC, KazanderDad commented
As a SME I've reviewed this NEP and find that it fills a useful purpose. It clarifies some of the potential points of confusion for anyone wishing to implement SBTs, including some that I ran into myself when deploying a new issuer recently. 

I might suggest rethinking the hashing requirement of Base64 encoded SHA256. While we can recognize that this - if done right - is a little more compact with 44 characters; it is not a commonly available method and the risk for implementing wrong is high. Casual users who try to find online SHA256 hashing tools will almost exclusively find tools that instead output hexadecimal characters, resulting in a 64-character string. A very likely risk is that they will attempt to Base64-encode this string (instead of the binary), resulting in a much longer output than intended, and resulting in a lot of confusion. A more usable requirement might be "a SHA256 hash expressed as a hexadecimal string"

2024-02-06 15:58 UTC, frol reviewed
As a Contract Standards Work Group member, I reviewed and lean to approving this NEP. That said, I believe we reached the quorum here to approve it, and since it is just an extension to the existing NEP, I suggest we go ahead and merge it.

@robert-zaremba Please, update the CHANGELOG section with 1.1.0 version summarizing the change and the decision.

2024-02-23 14:59 UTC, frol approved these changes

2024-02-23 14:59 UTC, merged

2024-03-21 16:05 UTC, victorchimakanu commented
## NEP Status *(Updated by NEP Moderators)*

**Status: Voting** 

SME reviews:

* Contract Standards SME @KazanderDad: https://github.com/near/NEPs/pull/528#issuecomment-1916048845
* Contract Standards SME @fadeevab: https://github.com/near/NEPs/pull/528#pullrequestreview-1848562574

Contract Standards Work Group voting indications (❔ | 👍 | 👎 ):

* 👍 @frol https://github.com/near/NEPs/pull/528#pullrequestreview-1865638134
* ? @robert-zaremba
* 👍 @fadeevab https://github.com/near/NEPs/pull/528#pullrequestreview-1848562574