Rich online digital tokens
near/NEPs pull request #551
Opened 2024-06-22 11:49 UTC by cableguard

Minimal support for Rich Online Digital Tokens as described in the whitepaper at https://github.com/cableguard/roditwhitepaper/tree/main

2024-07-04 21:08 UTC, victorchimakanu commented
Thank you @cableguard   for submitting this NEP.

I would like to ask the @near/working-groups members to assign 2 Technical Reviewers to complete a technical review.

(see expectations below).

Just for clarity, Technical Reviewers play a crucial role in scaling NEAR ecosystem as they provide their in-depth expertise in the niche topic while work group members can stay on guard of the NEAR ecosystem. 

The discussions may get too deep and it would be inefficient for each WG member to dive into every single comment, so NEAR Developer Governance [designed this process](https://github.com/near/NEPs/blob/master/neps/nep-0001.md) that includes subject matter experts helping us to scale by writing a summary with the raised concerns and how they were addressed.

2024-07-09 07:13 UTC, cableguard commented
Looking forward to the @near/working-groups to assign the technical reviewers. Is there anything I can do to help?

2024-09-16 16:25 UTC, fadeevab commented
@cableguard I'm from @near/working-groups , I can start a review, is it still relevant?

2024-09-17 07:33 UTC, cableguard commented
@fadeevab I would love for the review to start. This is particularly relevant now as besides a VPN implementation, I am now completing a MVP that leverages RODIT for stateless mutual API authentication, including webhooks. It is not hard to manage RODIT using only NEAR CLI, but standardization can only bring benefits.

2024-09-17 13:16 UTC, fadeevab requested changes
The summary of my initial review:

1. The NEP must be structured in such a way that provides a quick easy insight into the subject matter and a technical specification that would be easy to use by developers.
2. The protocol is not fully clear, I need more time to analyze it.
3. Diagrams should be included for better understanding.
4. Formatting must be fixed across the document.
5. Unnecessary information must be removed. I pointed out 1 concrete issue so far.
 
The document is a bit overloaded overall.

2024-09-17 17:23 UTC, cableguard commented
Thanks @fadeevab I will implement the necessary improvements over the next few days

2024-09-27 08:46 UTC, flmel commented
@cableguard 
Those could be of help
https://github.com/near/NEPs/blob/master/neps/nep-0001.md 
https://github.com/near/NEPs/blob/master/nep-0000-template.md

2025-02-20 14:47 UTC, flmel commented
I will assume this NEP is inactive and label as retracted for now. If anyone picks the NEP up again, please ping NEP moderators to make it active.

2025-02-21 11:09 UTC, rodit-org commented
@flmel I am completing the full demo that will make this NEP far easier to understand and process. No problem marking it retracted while the demo is finalized.

2025-07-16 13:24 UTC, gagdiez commented
As the moderator, I assume this PR is no longer active given that there was no activity for over two months. Therefore, I am closing it. If anyone is interested in reopening this PR, please submit a new one.

2025-07-16 13:24 UTC, closed without merging